### ISSUE TITLE
Add fabric methods for FixtureValue class

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#135]
Add 3 `public static methods` for constructing `com.github.vkorobkov.jfixtures.domain.Value` class in more clean ways than it is now:

1. ~`of(Object value)` basically should invoke constructor, but if `value instance of Value` should just return the `value`~

2. `ofSql(String sql)` (` return PREFIX_SQL + sql`)
3. `ofText(String text`) (`return PREFIX_TEXT + sql`)
4. `ofNull()` (`return NULL_VALUE`)

**Comment by vkorobkov** [comment]
I'll take the first part - method `of` right now to unblock the further progress

**Comment by vkorobkov** [comment]
Ok, the first part is on review -https://github.com/vkorobkov/jfixtures/pull/148

**Comment by rodionovsasha** [comment]
PR https://github.com/vkorobkov/jfixtures/pull/150 has been merged
