### ISSUE TITLE
Make Tables's value constructor private

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#137]
Make Fixture's value constructor private: `com.github.vkorobkov.jfixtures.domain.Value#Value` and use factory method `com.github.vkorobkov.jfixtures.domain.Value#of` every where instead

**Comment by rodionovsasha** [comment]
PR https://github.com/vkorobkov/jfixtures/pull/151

**Comment by rodionovsasha** [comment]
PR #151 merged
