### ISSUE TITLE
Allow FixtureRow#withBaseColumns to consume either Object or FixtureValue

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#138]
Allow `com.github.vkorobkov.jfixtures.loader.FixtureRow#withBaseColumns` to consume either `Object` or `FixtureValue`.

So the signature should be changed into:
```java
public FixtureRow withBaseColumns(Map<String, Object> base)
```
Use `com.github.vkorobkov.jfixtures.util.CollectionUtil#mapValues` and `com.github.vkorobkov.jfixtures.loader.FixtureValue#of`(from [here](https://github.com/vkorobkov/jfixtures/issues/135)) to make the transformation.

`com.github.vkorobkov.jfixtures.loader.FixtureRowTest` could be simplified accordingly since it does not have to feed `#withBaseColumns` with `FixtureValue`, constructing them before.

`com.github.vkorobkov.jfixtures.config.structure.tables.Tables#getDefaultColumns` should be simplified as well, now it can return `Map<String, Object>` instead of `Map<String, FixtureValue>`, and this transformation can be removed: `return CollectionUtil.mapValues(columns, FixtureValue::new);`

**Comment by rodionovsasha** [comment]
PR https://github.com/vkorobkov/jfixtures/pull/152

**Comment by rodionovsasha** [comment]
PR #152 merged
