### ISSUE TITLE
Add columns(Object ... keyValuePairs) method to Row class

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#154]
Extend `com.github.vkorobkov.jfixtures.domain.Row` class with a new method:
```java
public Row columns(Object... keyValuePairs)
```

The usage of this method will be:
```java
row.columns(
  "name", "Vlad",
  "age", 30,
  "hobby", "sleeping"
);
```

So the method should:
* Elements order should be preserved and tested. So use `LinkedHashMap` internally 
* Check that `keyValuePairs.length % 2 == 0`, otherwise, it should throw `IllegalArgumentException`
* Every odd(1, 3, ...) object is column name and should be checked with `instanceof String`, otherwise, an `IllegalArgumentException` should be thrown
* Every even(2, 4, ...) object is a column value
* Method should convert input array into `Map<String, Object>` and then should call `com.github.vkorobkov.jfixtures.domain.Row#columns(Map<String, Object> toMerge)` from https://github.com/vkorobkov/jfixtures/issues/153

**Comment by rodionovsasha** [comment]
PR https://github.com/vkorobkov/jfixtures/pull/158

**Comment by rodionovsasha** [comment]
https://github.com/vkorobkov/jfixtures/pull/158 merged
