### ISSUE TITLE
Add builder methods to Row

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#155]
Add builder methods to Row`com.github.vkorobkov.jfixtures.domain.Row`:
* `column(String name, Object value)`
* `nullColumn(String name)`
* `sqlColumn(String name, String sql)`
* `textColumn(String name, String text)`

Every of these methods should construct `com.github.vkorobkov.jfixtures.domain.Value` internally, create a singleton map and to pass this map into `com.github.vkorobkov.jfixtures.domain.Row#columns(Map<String, Object> toMerge)`, so the output object is a new instance. The source object should not be mutable

**Comment by rodionovsasha** [comment]
https://github.com/vkorobkov/jfixtures/pull/163 merged
