### ISSUE TITLE
Add factory methods for Row construction

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#156]
Add a set of static factory methods for instantiating `com.github.vkorobkov.jfixtures.domain.Row`:
* `ofName(String name)`
* `of(String name, Map<String, Object> columns)`
* `of(String name, Object... keyValuePairs)`

Make all existing constructors private and start using these factory methods instead in the code/tests

**Comment by rodionovsasha** [comment]
https://github.com/vkorobkov/jfixtures/pull/174 merged
