### ISSUE TITLE
Ability to load tables from Map of Maps of Maps

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#167]
Like from groovy code:
```groovy
[
  users: [
    vlad: [id: 5, age: 30],
    homer: [id: 6, age: 40]
  ],
  comments: [:]
]
```

Such easy thing maybe extremely useful to construct fixtures from such languages like groovy/jruby/etc which have built-in literals for defining maps

**Comment by rodionovsasha** [comment]
Git branch https://github.com/vkorobkov/jfixtures/tree/feature/map-of-maps

**Comment by vkorobkov** [comment]
@rodionovsasha please create a PR as soon as it is ready ❤️

**Comment by rodionovsasha** [comment]
PR https://github.com/vkorobkov/jfixtures/pull/196/files

**Comment by rodionovsasha** [comment]
merged
