### ISSUE TITLE
Fluent API for `Table` class

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#176]
Fluent API for `com.github.vkorobkov.jfixtures.domain.Table`.

Each point of DoD could be a separate PR so review goes faster:
* public constructor should be changed to private and should be replaced with static factory methods:
```java
static Table ofName(String name);
static Table of(String name, Row... rows);
static Table of(String name, Collection<Row> rows);
static Table ofRow(String name, String row, Map<String, Object> columns);
static Table ofRow(String name, String row, Object... keyValuePairs);
```

* Add methods to add new rows in batch:
```java
Table addRows(Row... rows);
Table addRows(Collection<Row> rows);
```

* Add method for adding a single row:
```java
Table addRow(String row, Map<String, Object> columns);
Table addRow(String row, Object... keyValuePairs);
```

**Comment by rodionovsasha** [comment]
1. https://github.com/vkorobkov/jfixtures/pull/177/files

**Comment by rodionovsasha** [comment]
https://github.com/vkorobkov/jfixtures/pull/179
https://github.com/vkorobkov/jfixtures/pull/180
