### ISSUE TITLE
Add loger and minimal verbosity

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#41]
No new compile-time dependencies should be added - provided scope only.

Probably, at minimum, there might be following logs:
```
WARN: file ".cong.yml" not found, using defaults
Processing table "users"
Processing table "comments"
Processing table "permissions"
Processing table "photos"
```

**Comment by rodionovsasha** [comment]
done https://github.com/vkorobkov/jfixtures/pull/59
