### ISSUE TITLE
Support .yaml file extension

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#76]
[YML files have _two_ valid possible extensions](https://en.wikipedia.org/wiki/YAML): `.yml` and `.yaml`

Currently we _do not_ support `.yaml` extension and we need to fix it before the public release.

1. `com.github.vkorobkov.jfixtures.config.ConfigLoader` 
Should lookup for `.conf.yaml` first, in case of failure should lookup fpr `.conf.yml`

2. `com.github.vkorobkov.jfixtures.loader.FixturesLoader#isYml` should be fixed:
```java
.endsWith(".yml") || .endsWith(".yaml")
```
There is an edge case here: if the same fixture exists with both extensions(like `users.yaml` and `users.yml` we need to throw an exception with a readable message)

**Comment by rodionovsasha** [comment]
PR https://github.com/vkorobkov/jfixtures/pull/85

**Comment by rodionovsasha** [comment]
merged to master as 1.0.2.6. release
