### ISSUE TITLE
Disallow dots in folder names

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#88]
So sub folders with fixtures can not have dots to avoid collisions like below:
```yml
+ old/
  + searches/
    log.yaml        # old.searches.log
+ old.searches/
  log.yaml          # also old.searches.log?
```
Instead, an exception should occur when dot in a folder name is detected.

**Comment by rodionovsasha** [comment]
PR: https://github.com/vkorobkov/jfixtures/pull/107

**Comment by rodionovsasha** [comment]
https://github.com/vkorobkov/jfixtures/pull/110 merged to master
