### ISSUE TITLE
Uppercase `null`to `NULL`

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#89]
Yaml has two valid `null` types: `~` and `null` as per [snake yaml documentation](https://bitbucket.org/asomov/snakeyaml/wiki/Documentation)

Both currently translate to `null` in output SQL code. We need to uppercase `null` so it becomes `NULL` and to cover this scenario with tests:
1. `~` -> `NULL`
2. `null` -> `NULL`
3. `Null` -> `NULL`
4. `nULL` -> `NULL`
5. `nulla` -> `'nulla'`

**Comment by rodionovsasha** [comment]
PR https://github.com/vkorobkov/jfixtures/pull/93

**Comment by rodionovsasha** [comment]
issue fixed and released v1.0.27
